### ISSUE TITLE
PCB CAD Design files?

### ISSUE THREAD

**Issue by glynhudson** [Protoneer/WifiPixels#9]
Hi, Nice design. 

I works for @openenergymonitor, together with @davehun I would like to make some changes to the design, would it be possible for you to publish the CAD PCB design files? Eagle CAD or otherwise? I will obvious make any derivatives totally open hardware. 

Ideas we have is to add a temperature sensor and design into an enclosure. 

Thanks,

**Comment by Protoneer** [comment]
Hi. Sorry for the delay. I have added the CAD files under the hardware folder. I use Kicad for my PCB designs.

**Comment by glynhudson** [comment]
Thanks a lot, I'll let you know how I get on and feedback any designs
designs
- sent from my mobile device
